title:
  ja: 'サイトタイトル'
  en: 'Site title'
rootdir:
  ja: ./
  en: ../
homedir:
  ja: ./
  en: en/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
gems: [autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
