title:
  ja: SkyWay - Enterprise Cloud WebRTC Platform
  en: ECLWebRTC - Enterprise Cloud WebRTC Platform
rootdir:
  ja: ./
  en: ../
homedir:
  ja: ./
  en: en/
og_image:
  ja: /images/skyway-ogp.png
  en: /images/eclwebrtc-ogp.png

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..2
theme: minima
gems: [autoprefixer-rails, jekyll-assets]
sass:
    sass_dir: _sass
